### PR TITLE
fix(gitpod): fix Docker command not found

### PR DESCRIPTION
**Pull request by ajhalili2006**
## Changelog

* Add an few `RUN` stuff for installing Docker and Docker Compose, plus additional tools.
* Added an bit of hack to check if Postgres server is up on each bashrc eval.
* Bring back DCO stuff, plus added Gitpod workspace image building scripts in `package.json`.
* Changed references of `docker compose` to `docker-compose` in `docker/package.json`
* Fixes some entrypoint script issues, as per https://github.com/hydralite/hydralite/commit/1bfa7420e6d920f30dcc15f214516a00346053e9.

## Previous changelogs

* https://github.com/hydralite/hydralite/pull/131

### CODE REVIEW

**Comment by 1chiSensei** [comment]
shouldnt the title be `fix(gitpod): ...`

**Comment by ajhalili2006** [comment]
> shouldnt the title be `fix(gitpod): ...`

While the commit logs have these, I think I agreed with you.

**Comment by ajhalili2006** [comment]
Hey, @fullstackslayer. Can you try to build the image from this PR on your Windows 10 machine

**Comment by ajhalili2006** [comment]
Hey, @fullstackslayer. Can you try to build the image from this PR on your Windows 10 machine

**Review by fullstackslayer — APPROVED** [review]

**Pull request merged**
