### PR TITLE
chore(api): remove joinDate in prisma schema as createdAt exists

### PR DESCRIPTION
**Pull request by eternalmoon1234**
Found a minor thing, joinDate is not needed because createdAt exists.

### CODE REVIEW

**Comment by eternalmoon1234** [comment]
idk why it says 25 files updated, i think the cli dir did some randoms stuff

**Comment by eternalmoon1234** [comment]
just found another mistake in the readme so i decided to add it because why not

**Review by fullstackslayer — CHANGES_REQUESTED** [review]
cool, could you remove the rust generated stuff before I merge it tho

**Comment by eternalmoon1234** [comment]
sure

**Comment by eternalmoon1234** [comment]
done

**Comment by eternalmoon1234** [comment]
Can you merge

**Comment by fullstackslayer** [comment]
sorry i forgot

**Comment by fullstackslayer** [comment]
merging now

**Review by fullstackslayer — APPROVED** [review]

**Pull request merged**
