### PR TITLE
Improve Dockerfile + add new scopes for Commitlint

### PR DESCRIPTION
**Pull request by ajhalili2006**
## Background

I'm working on adding support for Docker Compose and the Dockerfile for running Hydralite stuff, but since @f1shy-dev submitted their PR to add these first, I need to mess up with the resolving conflicts to keep things in sync.

## Changelog

* Add 3 more scopes to Commitlint (`docker` is for Docker Compose stuff and Dockerfiles, `gitpod` is for custom Gitpod workspace Dockerfile and configuration, and `devcontainer` for everything about Dev Containers inside VS Code) - **That's the reason why the Commitlint CI is failing. Please `git merge` them manually if branch protections are also required for repository/organization admins.**
* Fix indention issues on `.gitpod.yml`
* Hard-code frontend and backend ports because you need to prefix them first before doing `docker-compose up`., among other things. Also added database stuff for Hydralite in Compose (you still need to provide your own Redis configuration, among other stuff).
* Combine build stuff into one RUN to optimize build times.
* Add Docker entry point script to handle things when using `docker run` way of starting the servers.
* Added more scripts in `package.json`, including commit and Docker stuff. I'll assume that Hydralite will adopt [DCO](https://developercertificate.org) instead of hiring a legal team for writing a CLA, which is considered a barrier for new contributors.
* Update README because RIP setup scripts (aka `setup.cmd` and `setup.sh`). Also added some docs in the `.devcontainer` regarding what's the contents.

### CODE REVIEW

**Comment by ajhalili2006** [comment]
Of course, you should [use Kubernetes or Docker Swarm, not Docker Compose](https://stackoverflow.com/questions/47536536/whats-the-difference-between-docker-compose-and-kubernetes#47537046), on running Hydralite in production. See my note in the Compose file btw.

**Comment by ajhalili2006** [comment]
Also, the Commitlint Ci isn't failing. WHHHHAAATTTTT?

**Comment by firecraftgaming** [comment]
> Also, the Commitlint Ci isn't failing. WHHHHAAATTTTT?

I think the commitlint doesnt fail if your pr includes something that changes it

**Comment by fullstackslayer** [comment]
oh boy 

this is a big one :p

thanks for the contribution! gonna merge now

**Review by fullstackslayer — APPROVED** [review]

**Comment by ajhalili2006** [comment]
@fullstackslayer Did you forgot to merge? Also, lemme fix da conflicts first.

**Comment by fullstackslayer** [comment]
> @fullstackslayer Did you forgot to merge? Also, lemme fix da conflicts first.

yeah lmao

I was gonna click the button but it spammed conflicts ;-;

sorry about that - sure tell me when you've resolved the conflicts

**Comment by ajhalili2006** [comment]
@fullstackslayer Just squashed conflicts and shipped https://github.com/hydralite/hydralite/pull/131/commits/d106c628dc1ec249520e54389821e6a27ed7c8ec. 

Happy merging! =)

**Comment by fullstackslayer** [comment]
pog thanks!

**Pull request merged**
